# Generated by Django 5.0.3 on 2024-04-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='confirm_password',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
