# Generated by Django 5.0.3 on 2024-04-11 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teks', '0002_data_confirm_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='phone',
            new_name='username',
        ),
    ]
