# Generated by Django 5.0.3 on 2024-04-16 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teks', '0003_rename_phone_data_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'managed': True, 'verbose_name': 'data', 'verbose_name_plural': 'datas'},
        ),
        migrations.AlterModelTable(
            name='data',
            table='',
        ),
    ]
