# Generated by Django 5.0.3 on 2024-03-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aakash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('is_published', models.BooleanField(default=False)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'data',
                'verbose_name_plural': 'datas',
            },
        ),
    ]
