# Generated by Django 5.0.3 on 2024-03-19 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aakash',
            new_name='data',
        ),
    ]
