# Generated by Django 5.0.3 on 2024-03-21 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_data_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='video',
            field=models.FileField(null=True, upload_to='videos'),
        ),
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 3, 22, 0, 44, 31, 120865)),
        ),
    ]
